/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
    $('.turnbox').each(function(i, item){
        var box_id = this.id.substr(3);
        var box_name = localStorage.getItem('mytyot.box.'+box_id+'.name');
        console.log('box '+box_id+' has name '+box_name);
        if (box_name == null) {
            console.log('showing form_'+box_id);
            $('#'+this.id).hide();
            $('#form_'+box_id).show();
        } else {
            var activity = localStorage.getItem('mytyot.box.'+box_id+'.what');
            var when = localStorage.getItem('mytyot.box.'+box_id+'.when');
            var current = localStorage.getItem('mytyot.box.'+box_id+'.turn');
            show_turn(box_id, box_name, activity, when, current);
            console.log('showing the turner for '+box_id);
            $('#'+this.id).show();
            $('#form_'+box_id).hide();
        }
    });    
    
    /*

 getGirls(refreshGirls); // experimental
 
    console.log("after getGirls");
     var now = new Date();
    tf = document.getElementById('text1');
    var truncdate = ""+now;
    var td = truncdate.substr(0,24);
 
    var x = document.getElementsByTagName('div');
    for(i=0; i<x.length; i++) {
        var y = x[i];
        var id = y.getAttribute('id');
        if (id && id.substr(0, 7) == 'button_') {
            person = id.substr(7);
        console.log("PERSON = "+person);
            var current = localStorage.getItem('turn_'+person);
            var tf = document.getElementById('turn_'+person);
            tf.innerHTML = "Food with "+person+": "+current;
            var td = localStorage.getItem('when_'+person);
            tf = document.getElementById('when_'+person);
            tf.innerHTML = 'Last changed: ' + td;
        }
    }
    */
}

function html_for_person(person)
{
    var html = '<div><div id="button_@PERSON@"><button type="button" id="button_@PERSON@">SWAP</button><span id="turnx_@PERSON@">PERSON</span><span id="when_@PERSON@">WHEN</span></div>';
    var regexp = new RegExp('@'+person+'@', 'g');
    console.log(regexp);
    return html.replace(regexp, person);
}

function add_database_people(list)
{
    for(i=0; i<list.length; i++) {
        var add = html_for_person(list[i]);
          $('#content').append(add);
        $('#turnx_'+person).text('PERSON '+person);
    }
}


function myClickHandler(event)
{
    var myperson = event.toElement.parentNode.id.substr(7);
    var box_name = localStorage.getItem('mytyot.box.'+myperson+'.name');
    var current = localStorage.getItem('mytyot.box.'+myperson+'.turn');
    var when = localStorage.getItem('mytyot.box.'+myperson+'.when');
    var what = localStorage.getItem('mytyot.box.'+myperson+'.what');
    var whonext = box_name;
    if (current == box_name) {
        whonext = 'Me';
    }
    console.log(box_name+' => '+current+' => '+whonext);

    localStorage.setItem('mytyot.box.'+myperson+'.turn', whonext);
    
    // faff to update the date
    var now = ""+new Date();
    var td = now.substr(0,24);
    localStorage.setItem('mytyot.box.'+myperson+'.when', td);
    show_turn(myperson, box_name, what, when, whonext);
}


function myFormHandler(event)
{
    // Insert Code Here    var myperson = event.toElement.parentNode.id.substr(7);
    var myform = event.toElement.parentNode.id.substr(12);
    var activity = $('#form_what_'+myform).val();
    var who = $('#form_who_'+myform).val();
    console.log('form '+myform+' clicked with "'+activity+' with '+who);
    localStorage.setItem('mytyot.box.'+myform+'.name', who);
    localStorage.setItem('mytyot.box.'+myform+'.what', activity);
    localStorage.setItem('mytyot.box.'+myform+'.turn', 'Me');
    show_turn(myform, who, activity, 'Never', 'Me');
}

function show_turn(myform, who, activity, when, whonext)
{
    $('#turn_'+myform).html(activity+' with '+who+': '+whonext);
    $('#when_'+myform).html(when);
    $('#form_'+myform).find(':input').attr('disabled', true);
    $('#form_'+myform).hide();
    $('#box'+myform).show();
}
